# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shm_update.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shm_update.proto',
  package='',
  serialized_pb=_b('\n\x10shm_update.proto\"u\n\tShmUpdate\x12\x1b\n\x03var\x18\x01 \x03(\x0b\x32\x0e.ShmUpdate.Var\x1aK\n\x03Var\x12\x0b\n\x03tag\x18\x01 \x02(\x05\x12\x10\n\x08intValue\x18\x02 \x01(\x05\x12\x12\n\nfloatValue\x18\x03 \x01(\x02\x12\x11\n\tboolValue\x18\x04 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SHMUPDATE_VAR = _descriptor.Descriptor(
  name='Var',
  full_name='ShmUpdate.Var',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='ShmUpdate.Var.tag', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intValue', full_name='ShmUpdate.Var.intValue', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatValue', full_name='ShmUpdate.Var.floatValue', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boolValue', full_name='ShmUpdate.Var.boolValue', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=137,
)

_SHMUPDATE = _descriptor.Descriptor(
  name='ShmUpdate',
  full_name='ShmUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var', full_name='ShmUpdate.var', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SHMUPDATE_VAR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=137,
)

_SHMUPDATE_VAR.containing_type = _SHMUPDATE
_SHMUPDATE.fields_by_name['var'].message_type = _SHMUPDATE_VAR
DESCRIPTOR.message_types_by_name['ShmUpdate'] = _SHMUPDATE

ShmUpdate = _reflection.GeneratedProtocolMessageType('ShmUpdate', (_message.Message,), dict(

  Var = _reflection.GeneratedProtocolMessageType('Var', (_message.Message,), dict(
    DESCRIPTOR = _SHMUPDATE_VAR,
    __module__ = 'shm_update_pb2'
    # @@protoc_insertion_point(class_scope:ShmUpdate.Var)
    ))
  ,
  DESCRIPTOR = _SHMUPDATE,
  __module__ = 'shm_update_pb2'
  # @@protoc_insertion_point(class_scope:ShmUpdate)
  ))
_sym_db.RegisterMessage(ShmUpdate)
_sym_db.RegisterMessage(ShmUpdate.Var)


# @@protoc_insertion_point(module_scope)
